// <auto-generated />
using Asynclnn.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Asynclnn.Migrations
{
    [DbContext(typeof(AsyncDbContext))]
    [Migration("20190130195539_newseededdata")]
    partial class newseededdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Async.Models.Amenities", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "coffeeMachine"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Aircondition"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Microwave"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Stove"
                        },
                        new
                        {
                            ID = 5,
                            Name = "washer"
                        });
                });

            modelBuilder.Entity("Async.Models.Hotel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Name");

                    b.Property<string>("phone");

                    b.HasKey("ID");

                    b.ToTable("Hotel");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "seattle,wA",
                            Name = "Async seattle",
                            phone = "425-344-6390"
                        },
                        new
                        {
                            ID = 2,
                            Address = "1123 newyork st",
                            Name = "Async Newyork",
                            phone = "425-344-6290"
                        },
                        new
                        {
                            ID = 3,
                            Address = "278 california st",
                            Name = "Async Boston",
                            phone = "206-344-6390"
                        },
                        new
                        {
                            ID = 4,
                            Address = "1234 madison st",
                            Name = "Async Portland",
                            phone = "371-344-6390"
                        },
                        new
                        {
                            ID = 5,
                            Address = "Edmonds,wA",
                            Name = "Async Edmonds",
                            phone = "425-344-6790"
                        });
                });

            modelBuilder.Entity("Async.Models.HotelRoom", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Rate");

                    b.Property<int>("RoomID");

                    b.Property<int>("RoomNumber");

                    b.Property<string>("petFreindly");

                    b.HasKey("ID");

                    b.ToTable("HotelRooms");
                });

            modelBuilder.Entity("Async.Models.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Layouts");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Layouts = "layout.onebed",
                            Name = "Kingfu"
                        },
                        new
                        {
                            ID = 2,
                            Layouts = "layout.onebed",
                            Name = "Queenann"
                        },
                        new
                        {
                            ID = 3,
                            Layouts = "layout.studio",
                            Name = "suit"
                        },
                        new
                        {
                            ID = 4,
                            Layouts = "layout.twobed",
                            Name = "double"
                        },
                        new
                        {
                            ID = 5,
                            Layouts = "layout.onebed",
                            Name = "shalom"
                        },
                        new
                        {
                            ID = 6,
                            Layouts = "layout.onebed",
                            Name = "ocean"
                        });
                });

            modelBuilder.Entity("Async.Models.RoomAmenities", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmenitiesID");

                    b.Property<int>("RoomID");

                    b.HasKey("ID");

                    b.ToTable("RoomAmenities");
                });
#pragma warning restore 612, 618
        }
    }
}
